server:
  port: 8080

spring:

  application:
    name: event-gateway

  datasource:
    url: jdbc:h2:mem:gatewaydb

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

account:
  service:
    url: http://account-service:8081


resilience4j:

  circuitbreaker:

    instances:

      accountService:

        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        failureRateThreshold: 50

        waitDurationInOpenState: 15s

  retry:

    instances:

      accountService:

        maxAttempts: 3

        waitDuration: 1s

  timelimiter:

    instances:

      accountService:

        timeoutDuration: 3s

management:

  tracing:

    enabled: true

    sampling:

      probability: 1.0

  endpoints:

    web:

      exposure:

        include: health,metrics,prometheus
